import type { TarotCard, Spread } from './types';

export const TAROT_DECK: TarotCard[] = [
    // Major Arcana
    { name: 'Głupiec', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/RWS_Tarot_00_Fool.jpg/400px-RWS_Tarot_00_Fool.jpg' },
    { name: 'Mag', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/RWS_Tarot_01_Magician.jpg/400px-RWS_Tarot_01_Magician.jpg' },
    { name: 'Papieżyca', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/RWS_Tarot_02_High_Priestess.jpg/400px-RWS_Tarot_02_High_Priestess.jpg' },
    { name: 'Cesarzowa', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/RWS_Tarot_03_Empress.jpg/400px-RWS_Tarot_03_Empress.jpg' },
    { name: 'Cesarz', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/RWS_Tarot_04_Emperor.jpg/400px-RWS_Tarot_04_Emperor.jpg' },
    { name: 'Papież', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/RWS_Tarot_05_Hierophant.jpg/400px-RWS_Tarot_05_Hierophant.jpg' },
    { name: 'Kochankowie', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_06_Lovers.jpg/400px-RWS_Tarot_06_Lovers.jpg' },
    { name: 'Rydwan', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/RWS_Tarot_07_Chariot.jpg/400px-RWS_Tarot_07_Chariot.jpg' },
    { name: 'Moc', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/RWS_Tarot_08_Strength.jpg/400px-RWS_Tarot_08_Strength.jpg' },
    { name: 'Pustelnik', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/RWS_Tarot_09_Hermit.jpg/400px-RWS_Tarot_09_Hermit.jpg' },
    { name: 'Koło Fortuny', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/RWS_Tarot_10_Wheel_of_Fortune.jpg/400px-RWS_Tarot_10_Wheel_of_Fortune.jpg' },
    { name: 'Sprawiedliwość', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/RWS_Tarot_11_Justice.jpg/400px-RWS_Tarot_11_Justice.jpg' },
    { name: 'Wisielec', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/RWS_Tarot_12_Hanged_Man.jpg/400px-RWS_Tarot_12_Hanged_Man.jpg' },
    { name: 'Śmierć', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/RWS_Tarot_13_Death.jpg/400px-RWS_Tarot_13_Death.jpg' },
    { name: 'Umiarkowanie', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/RWS_Tarot_14_Temperance.jpg/400px-RWS_Tarot_14_Temperance.jpg' },
    { name: 'Diabeł', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/RWS_Tarot_15_Devil.jpg/400px-RWS_Tarot_15_Devil.jpg' },
    { name: 'Wieża', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/RWS_Tarot_16_Tower.jpg/400px-RWS_Tarot_16_Tower.jpg' },
    { name: 'Gwiazda', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/RWS_Tarot_17_Star.jpg/400px-RWS_Tarot_17_Star.jpg' },
    { name: 'Księżyc', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/RWS_Tarot_18_Moon.jpg/400px-RWS_Tarot_18_Moon.jpg' },
    { name: 'Słońce', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/RWS_Tarot_19_Sun.jpg/400px-RWS_Tarot_19_Sun.jpg' },
    { name: 'Sąd Ostateczny', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/RWS_Tarot_20_Judgement.jpg/400px-RWS_Tarot_20_Judgement.jpg' },
    { name: 'Świat', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/RWS_Tarot_21_World.jpg/400px-RWS_Tarot_21_World.jpg' },
    // Wands
    { name: 'As Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Wands01.jpg/400px-Wands01.jpg' },
    { name: 'Dwójka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Wands02.jpg/400px-Wands02.jpg' },
    { name: 'Trójka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Wands03.jpg/400px-Wands03.jpg' },
    { name: 'Czwórka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Wands04.jpg/400px-Wands04.jpg' },
    { name: 'Piątka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Wands05.jpg/400px-Wands05.jpg' },
    { name: 'Szóstka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Wands06.jpg/400px-Wands06.jpg' },
    { name: 'Siódemka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Wands07.jpg/400px-Wands07.jpg' },
    { name: 'Ósemka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Wands08.jpg/400px-Wands08.jpg' },
    { name: 'Dziewiątka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Wands09.jpg/400px-Wands09.jpg' },
    { name: 'Dziesiątka Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Wands10.jpg/400px-Wands10.jpg' },
    { name: 'Giermek Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Wands11.jpg/400px-Wands11.jpg' },
    { name: 'Rycerz Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Wands12.jpg/400px-Wands12.jpg' },
    { name: 'Królowa Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Wands13.jpg/400px-Wands13.jpg' },
    { name: 'Król Buław', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Wands14.jpg/400px-Wands14.jpg' },
    // Cups
    { name: 'As Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Cups01.jpg/400px-Cups01.jpg' },
    { name: 'Dwójka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Cups02.jpg/400px-Cups02.jpg' },
    { name: 'Trójka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Cups03.jpg/400px-Cups03.jpg' },
    { name: 'Czwórka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Cups04.jpg/400px-Cups04.jpg' },
    { name: 'Piątka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Cups05.jpg/400px-Cups05.jpg' },
    { name: 'Szóstka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cups06.jpg/400px-Cups06.jpg' },
    { name: 'Siódemka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Cups07.jpg/400px-Cups07.jpg' },
    { name: 'Ósemka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Cups08.jpg/400px-Cups08.jpg' },
    { name: 'Dziewiątka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Cups09.jpg/400px-Cups09.jpg' },
    { name: 'Dziesiątka Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Cups10.jpg/400px-Cups10.jpg' },
    { name: 'Giermek Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Cups11.jpg/400px-Cups11.jpg' },
    { name: 'Rycerz Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Cups12.jpg/400px-Cups12.jpg' },
    { name: 'Królowa Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Cups13.jpg/400px-Cups13.jpg' },
    { name: 'Król Pucharów', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cups14.jpg/400px-Cups14.jpg' },
    // Swords
    { name: 'As Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Swords01.jpg/400px-Swords01.jpg' },
    { name: 'Dwójka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Swords02.jpg/400px-Swords02.jpg' },
    { name: 'Trójka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Swords03.jpg/400px-Swords03.jpg' },
    { name: 'Czwórka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Swords04.jpg/400px-Swords04.jpg' },
    { name: 'Piątka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Swords05.jpg/400px-Swords05.jpg' },
    { name: 'Szóstka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Swords06.jpg/400px-Swords06.jpg' },
    { name: 'Siódemka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Swords07.jpg/400px-Swords07.jpg' },
    { name: 'Ósemka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Swords08.jpg/400px-Swords08.jpg' },
    { name: 'Dziewiątka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Swords09.jpg/400px-Swords09.jpg' },
    { name: 'Dziesiątka Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords10.jpg/400px-Swords10.jpg' },
    { name: 'Giermek Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Swords11.jpg/400px-Swords11.jpg' },
    { name: 'Rycerz Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Swords12.jpg/400px-Swords12.jpg' },
    { name: 'Królowa Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Swords13.jpg/400px-Swords13.jpg' },
    { name: 'Król Mieczy', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Swords14.jpg/400px-Swords14.jpg' },
    // Pentacles
    { name: 'As Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Pents01.jpg/400px-Pents01.jpg' },
    { name: 'Dwójka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Pents02.jpg/400px-Pents02.jpg' },
    { name: 'Trójka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Pents03.jpg/400px-Pents03.jpg' },
    { name: 'Czwórka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Pents04.jpg/400px-Pents04.jpg' },
    { name: 'Piątka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Pents05.jpg/400px-Pents05.jpg' },
    { name: 'Szóstka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Pents06.jpg/400px-Pents06.jpg' },
    { name: 'Siódemka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Pents07.jpg/400px-Pents07.jpg' },
    { name: 'Ósemka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pents08.jpg/400px-Pents08.jpg' },
    { name: 'Dziewiątka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Pents09.jpg/400px-Pents09.jpg' },
    { name: 'Dziesiątka Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Pents10.jpg/400px-Pents10.jpg' },
    { name: 'Giermek Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Pents11.jpg/400px-Pents11.jpg' },
    { name: 'Rycerz Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Pents12.jpg/400px-Pents12.jpg' },
    { name: 'Królowa Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Pents13.jpg/400px-Pents13.jpg' },
    { name: 'Król Monet', imgSrc: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Pents14.jpg/400px-Pents14.jpg' },
];

export const SPREADS: Spread[] = [
    { name: 'Jedna karta', cardCount: 1, positions: ['Twoja ogólna energia lub odpowiedź'] },
    { name: 'Trzy karty', cardCount: 3, positions: ['Przeszłość', 'Teraźniejszość', 'Przyszłość'] },
    { name: 'Krzyż Celtycki (uproszczony)', cardCount: 5, positions: ['Sytuacja', 'Wyzwanie', 'Podstawa', 'Najbliższa przyszłość', 'Wynik'] },
];

export const CARD_BACK_URL = 'https://i.ibb.co/6gBgh3Y/card-back.png';